In [1]:
# import libraries

import numpy as np
import pandas as pd

In [2]:
# load data set
df = pd.read_csv("/content/FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding = "latin-1")

In [3]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [5]:
df.isna().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [6]:
df.shape

(60943, 12)

In [7]:
df.describe(include = 'all')

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943,60943.000000,60943,60943.000000,60943,60943,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
unique,NaN,49,NaN,119,NaN,18,5,NaN,NaN,NaN,NaN,NaN
top,NaN,Kenya,NaN,Milk - Excluding Butter,NaN,Domestic supply quantity,1000 tonnes,NaN,NaN,NaN,NaN,NaN
freq,NaN,1560,NaN,1262,NaN,5295,40933,NaN,NaN,NaN,NaN,NaN
mean,134.265576,NaN,2687.176706,NaN,3814.856456,NaN,NaN,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,NaN,146.055739,NaN,2212.007033,NaN,NaN,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,NaN,2501.000000,NaN,511.000000,NaN,NaN,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,NaN,2562.000000,NaN,684.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,NaN,2630.000000,NaN,5142.000000,NaN,NaN,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,NaN,2775.000000,NaN,5511.000000,NaN,NaN,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,NaN,2961.000000,NaN,5911.000000,NaN,NaN,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

**Q1.Group by Area for 2017, Highest Area?**

In [ ]:
groupbyA = df[['Y2017','Area']].groupby('Area').sum().sort_values('Y2017')
print(groupbyA)

                                  Y2017
Area
Sudan (former)                     0.00
Ethiopia PDR                       0.00
Comoros                           59.84
Seychelles                       442.34
Sao Tome and Principe          12662.63
Cabo Verde                     14650.74
Guinea-Bissau                  19102.77
Lesotho                        21267.96
Botswana                       22101.30
Djibouti                       22729.91
Gambia                         23154.18
Gabon                          27979.64
Liberia                        29342.20
Namibia                        29874.89
Central African Republic       29937.00
Congo                          41181.68
Togo                           49841.88
Mauritius                      51114.83
Eswatini                       54343.33
Sierra Leone                   55311.33
Chad                           71594.68
Rwanda                         73663.69
Zimbabwe                       75919.34
Senegal                        95681.15
Guinea                         98138.87
Burkina Faso                  101855.07
Zambia                        103223.77
Tunisia                       124167.20
Benin                         124771.22
Niger                         126707.58
Madagascar                    131197.73
Mali                          149928.33
Mauritania                    156665.46
Mozambique                    161407.98
Malawi                        181098.71
Uganda                        213950.38
Côte d'Ivoire                 224599.01
Angola                        229159.57
Cameroon                      232030.43
Sudan                         239931.92
Kenya                         264660.66
United Republic of Tanzania   322616.85
Algeria                       325644.27
Ghana                         337599.06
Morocco                       388495.36
Ethiopia                      448683.76
South Africa                  517590.54
Egypt                         866379.92
Nigeria                      1483268.23

**Q2. Total sum of wine produced in 2015 and 2018**

In [ ]:
df.groupby('Item').sum().loc[['Wine'],['Y2015', 'Y2018']]

<ipython-input-17-8a8148c497ba>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Item').sum().loc[['Wine'],['Y2015', 'Y2018']]

        Y2015    Y2018
Item
Wine  4251.81  4039.32

**Q4. Tuple- Assignment of variable**

In [75]:
y = [(2, 4), (7, 8), (1, 5, 9)]
x = y[1][1]
print(x)
xx = y[1][-1]
print(xx)

8
8

**Q7. Pandas DataFrame**

In [ ]:
ist = [[35,'Portugal','94'],[33,'Argentina', 93],[30, 'Brazil',92]]
col = ['Age','Nationality','Overall']
p1 = pd.DataFrame(ist, columns=col,index=[i for i in range(1,4)])
print(p1)

   Age Nationality Overall
1   35    Portugal      94
2   33   Argentina      93
3   30      Brazil      92

**Q8. Number of unique countries in the dataset**

In [ ]:
unique_countries = df['Area'].nunique()
print(unique_countries)

49

**Q.9 Groupby 'Element', Year of highest sum of Stock variation?**

In [ ]:
groupbystockvar = df.groupby('Element').sum().loc[['Stock Variation'], ['Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018']]
print(groupbystockvar)

                    Y2014     Y2015     Y2016     Y2017     Y2018
Element
Stock Variation  58749.83  34910.99  33140.12  54316.91  20577.91

In [ ]:
groupbystockvar.max()

Y2014    58749.83
Y2015    34910.99
Y2016    33140.12
Y2017    54316.91
Y2018    20577.91
dtype: float64

**Q10. Total number and precentage of missing data in 2014 to 3 decimal places**

In [ ]:
Y2016_missing_data = df.isna().sum().loc['Y2014']
missing_percent = round((Y2016_missing_data * 100 / len(df)), 3)
print(Y2016_mssing_data)
print(missing_percent)

1589
2.607

**Q11. Numpy Array Index**

In [ ]:
a = np.array([[94,89,63], [93,92,48], [92,94,56]])

In [ ]:
a[:2,1:]

array([[89, 63],
       [92, 48]])

**Group by 'Element' for 2017**

In [8]:
groupby = df.groupby("Element")["Y2017"].sum()
print(groupby)

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

**Q12**. **Groupby 'Element' and get the total number of sum for 'Processing' in** **2017**

In [ ]:
df.groupby('Element').sum().loc[['Processing'],['Y2017']]

<ipython-input-9-505b1d9b42bd>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Element').sum().loc[['Processing'],['Y2017']]

               Y2017
Element
Processing  292836.0

**Q15. Mean and standard deviation of dataset in 2017 to 2 decimal places**

---

In [ ]:
df.describe().loc[['mean', 'std'],['Y2017']]

            Y2017
mean   140.917765
std   1671.862359

**Q16. Year of the least correlation with 'Element Code'**

In [ ]:
df.corr()[['Element Code']].sort_values(by='Element Code', ascending=True)

<ipython-input-23-260bf1ba03c9>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()[['Element Code']].sort_values(by='Element Code', ascending=True)

              Element Code
Item Code        -0.024683
Area Code        -0.000209
Y2016             0.023444
Y2015             0.023889
Y2017             0.024254
Y2018             0.024279
Y2014             0.024457
Element Code      1.000000

In [68]:
groupbyM = df[['Y2015','Element','Area']].groupby(['Element','Area']).sum().sort_values('Y2015')
print(groupbyM)

                                           Y2015
Element                  Area
Stock Variation          South Africa   -7238.00
                         Sudan          -2748.00
                         Rwanda         -1429.00
                         Zambia         -1037.00
Residuals                South Africa    -893.00
...                                          ...
Production               Egypt         205548.03
Food                     Nigeria       231454.02
Domestic supply quantity Egypt         245789.22
Production               Nigeria       385670.13
Domestic supply quantity Nigeria       406045.65

[803 rows x 1 columns]

**Q17. Total Protein Supply quantity in 'Madagascar' in 2015**

In [72]:
df.set_index('Area').loc['Madagascar'].groupby('Element')[['Y2015']].sum()

                                           Y2015
Element
Domestic supply quantity                31214.98
Export Quantity                           494.75
Fat supply quantity (g/capita/day)         91.85
Feed                                     2070.22
Food                                    21120.65
Food supply (kcal/capita/day)            7685.00
Food supply quantity (kg/capita/yr)       871.59
Import Quantity                          1721.80
Losses                                   2176.00
Other uses (non-food)                    3957.12
Processing                               1803.00
Production                              29482.89
Protein supply quantity (g/capita/day)    173.05
Residuals                                -616.00
Seed                                      699.00
Stock Variation                          -505.00
Total Population - Both sexes           24234.00

**Q.18**

In [ ]:
S =[['him', 'sell'], [90,28,43]]

In [ ]:
S[0][1][1]

'e'

**Q20. Group by Area for 2017, 7th Lowest Area?**

In [13]:
groupbyA = df[['Y2017','Area']].groupby('Area').sum().sort_values('Y2017')
print(groupbyA)

                                  Y2017
Area
Sudan (former)                     0.00
Ethiopia PDR                       0.00
Comoros                           59.84
Seychelles                       442.34
Sao Tome and Principe          12662.63
Cabo Verde                     14650.74
Guinea-Bissau                  19102.77
Lesotho                        21267.96
Botswana                       22101.30
Djibouti                       22729.91
Gambia                         23154.18
Gabon                          27979.64
Liberia                        29342.20
Namibia                        29874.89
Central African Republic       29937.00
Congo                          41181.68
Togo                           49841.88
Mauritius                      51114.83
Eswatini                       54343.33
Sierra Leone                   55311.33
Chad                           71594.68
Rwanda                         73663.69
Zimbabwe                       75919.34
Senegal                        95681.15
Guinea                         98138.87
Burkina Faso                  101855.07
Zambia                        103223.77
Tunisia                       124167.20
Benin                         124771.22
Niger                         126707.58
Madagascar                    131197.73
Mali                          149928.33
Mauritania                    156665.46
Mozambique                    161407.98
Malawi                        181098.71
Uganda                        213950.38
Côte d'Ivoire                 224599.01
Angola                        229159.57
Cameroon                      232030.43
Sudan                         239931.92
Kenya                         264660.66
United Republic of Tanzania   322616.85
Algeria                       325644.27
Ghana                         337599.06
Morocco                       388495.36
Ethiopia                      448683.76
South Africa                  517590.54
Egypt                         866379.92
Nigeria                      1483268.23